name: Dokku Deployment
on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: deploy
        name: Deploy to Dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        env:
          TOKEN: ${{ secrets.TOKEN }}
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: 'dobrovoljc.tplinkdns.com'
          app-name: 'vegahq-dbot'
