name: 'Dokku Deployment'

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Deploy to Dokku
        uses: dokku/github-actions@v1
        with:
          git_remote_url: 'ssh://dokku@dobrovoljc.tplinkdns.com:22/vegahq-dbot'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
